site_name: quotes_convert
site_description: Convert matching double-quotes to single-quotes or vice versa in strings and streams.
site_author: Y. Siva Sai Krishna
site_url: "https://ysskrishna.github.io/quotes-convert"
repo_name: "ysskrishna/quotes-convert"
repo_url: "https://github.com/ysskrishna/quotes-convert"
copyright: Copyright &copy; 2026 Y. Siva Sai Krishna
docs_dir: docs

nav:
  - Home: index.md
  - API Reference: api-reference.md
  - Changelog: CHANGELOG.md
  - License: LICENSE

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_signature_annotations: true
            separate_signature: true
            docstring_style: google
            merge_init_into_class: true

theme:
  name: material
  locale: en
  features:
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.snippets:
      base_path: .

extra:
  keywords:
    - quotes
    - convert
    - single-quotes
    - double-quotes
    - strings
    - text-processing
    - streaming
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ysskrishna/quotes-convert

